export const env = {
	NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || '',
	NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
	METERED_TURN_URL: process.env.NEXT_PUBLIC_METERED_TURN_URL || '',
	METERED_TURN_USERNAME: process.env.NEXT_PUBLIC_METERED_TURN_USERNAME || '',
	METERED_TURN_CREDENTIAL: process.env.NEXT_PUBLIC_METERED_TURN_CREDENTIAL || '',
};


